@baseUrl = http://localhost:3001/v1/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaXAiOiIxMjAxNDAxOTQiLCJzdWIiOnsiaWQiOiJhNzU5MGE1MS1iMmEyLTRhZmMtYTM0Ni1kYjA0MmY3ZGJlMzIifSwicm9sZSI6W3sicm9sZSI6IkFETUlOIn0seyJyb2xlIjoiVVNFUiJ9XSwiaWF0IjoxNjk0ODAxMzEyLCJleHAiOjE2OTQ4ODc3MTJ9.5g6iJR6MjFS3u6UbgJ2taWq509NNgkgxiFIYNvQ4FxQ
### Get all absen
GET {{baseUrl}}/absen
Authorization: Bearer {{token}}

### Get absen by id
GET {{baseUrl}}/absen/e24111f5-48f4-4cbf-820d-d0a696541653
Authorization: Bearer {{token}}

### Creater absen 
POST {{baseUrl}}/absen HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "tanggal": "2023-09-14",
    "jamMasuk": "08:00:00",
    "jamBatas": "09:00:00",
    "jamKeluar": "17:00:00"
}


### Update absen
PATCH {{baseUrl}}/absen/e3b7954c-4116-4691-b90b-5fd85f6e2683 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "tanggal": "2030-09-12",
    "jamMasuk": "08:00:00",
    "jamBatas": "09:00:00",
    "jamKeluar": "17:00:00",
    "statusAbsenId": 2
}

### Get all user
GET {{baseUrl}}/user
Authorization: Bearer {{token}}

### create user
POST {{baseUrl}}/auth/signup HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nama": "Muslim",
    "nip": "120140100",
    "email": "muslim@gmail.com",
    "password": "masukaja123"
}

### login user
POST {{baseUrl}}/auth/signin HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nip": "120140194",
    "password": "masukaja123"
}

### logout user
POST {{baseUrl}}/auth/signout HTTP/1.1
Authorization: Bearer {{token}}

### get profile
GET {{baseUrl}}/user/me
Authorization: Bearer {{token}}